#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01) also add other subdomains to make our life easier
# How to Use: ./1-world_wide_web `domain` `subdomain`
# Function to display subdomain information
display_info() {
    domain="$1"
    subdomain="$2"
    subdomains=("www" "lb-01" "web-01" "web-02")
    if [ -n "$subdomain" ]; then
        subdomains=("$subdomain")
    fi
    for sub in "${subdomains[@]}"; do
        record=$(dig +short "$sub.$domain")
        if [ -n "$record" ]; then
            record_type=$(echo "$record" | awk '{print toupper($1)}')
            echo "The subdomain $sub is a $record_type record and points to $record"
        fi
    done
}

if [ "$#" -eq 2 ]; then
    display_info "$1" "$2"
elif [ "$#" -eq 1 ]; then
    display_info "$1"
else
    echo "Usage: $0 domain [subdomain]"
fi
