#!/usr/bin/env bash
# Configure your domain zone so that the subdomain www points to your load-balancer IP (lb-01) also add other subdomains to make our life easier
# Usage: ./1-world_wide_web `domain` `subdomain`

domain_information () {
    local line
    line=$(dig +short "$2"."$1" | tail -n1)
    if [ -n "$line" ]; then
        local subdomain=$(echo "$line" | awk '{print $1}')
        local record=$(echo "$line" | awk '{print $2}')
        local destination=$(echo "$line" | awk '{print $3}')
        echo "The subdomain $subdomain is a $record record and points to $destination"
    else
        echo "No record found for $2.$1"
    fi
}

if [ "$#" -eq 1 ]; then
  domain_information "$1" "www"
  domain_information "$1" "lb-01"
  domain_information "$1" "web-01"
  domain_information "$1" "web-02"
elif [ "$#" -eq 2 ]; then
  domain_information "$1" "$2"
else
  echo "Usage: $0 domain [subdomain]"
fi
