#!/usr/bin/env bash
# a script that install nginx and configure it for ubuntu

sudo apt-get update
sudo apt-get install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html > /dev/null
sudo service nginx start
