#!/usr/bin/env bash
# a script that install nginx and configure it for ubuntu
# machine
apt-get -y update
apt-get -y install nginx
echo "Hello World!" > /var/www/html/index.nginx-debian.html
service nginx start
