#!/usr/bin/env bash
# a script that install nginx and configure it for ubuntu

sudo apt-get update
sudo apt-get install -y nginx
sudo sed -i 's/^.*listen.*$/    listen 80;/' /etc/nginx/sites-available/default
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart
