#!/usr/bin/env bash
# write a bash script that redirect  to another page
# the redirection must be '301 Moved Permanently'
# Install Nginx if not already installed

sudo apt update -y
sudo apt install -y nginx
ufw allow 'Nginx HTTP'
echo 'Hello World!' > /var/www/html/index.nginx-debian.html
sudo sed -i '/server_name localhost;/a \
\ \ \ \ location \/redirect_me { \
\ \ \ \ \ \ \ \ return 301 http:\/\/twitter.com\/home; \
\ \ \ \ }' /etc/nginx/sites-available/default

sudo service nginx start
