#!/usr/bin/env bash
# write a bash script that redirect  to another page
# the redirection must be '301 Moved Permanently'

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/Toeseen188 permanent;" /etc/nginx/sites-enabled/default

sudo service nginx restart
