#!/usr/bin/env bash
# write a bash script that redirect  to another page
# the redirection must be '301 Moved Permanently'
# Installs, configures, and starts the server

sudo apt update
sudo apt install -y nginx
echo "server {
    listen 80;
    server_name localhost;

    location /redirect_me {
        return 301 https://twitter.com/snurudeen21 permanent;
    }
}" | sudo tee /etc/nginx/sites-available/redirect.conf > /dev/null

sudo ln -s /etc/nginx/sites-available/redirect.conf /etc/nginx/sites-enabled/


sudo service nginx start
