#!/usr/bin/env bash
# write a bash script that redirect  to another page
# the redirection must be to 404 error code
# Ceci n'est pas une page

sudo apt-get update -y
sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

sudo sed -i "/listen 80 default_server;/a rewrite ^/redirect_me https://twitter.com/Toeseen188 permanent;" /etc/nginx/sites-enabled/default

echo "Ceci n'est pas une page\n" | sudo tee /usr/share/nginx/html/page_error_404.html

sudo sed -i "37i error_page 404 /page_error_404.html;\nlocation = /page_error_404.html {\nroot /usr/share/nginx/html; \ninternal;\n}\n" /etc/nginx/sites-enabled/default

sudo service nginx restart
