#!/usr/bin/env bash
# find out what's keeping your Ubuntu Nginx from listening on port 80 and fix
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx start
kill "$(pgrep 'nginx' | head -1)"
