#!/usr/bin/env bash
# find out what's keeping your Ubuntu Nginx from listening on port 80 and fix
rm /etc/nginx/sites-enabled/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
service nginx restart
