#!/usr/bin/env bash
# configures an Ubuntu server to: localhost resolves to 127.0.0.2, facebook.com resolves to 8.8.8.8
echo "127.0.0.2 localhost" | sudo tee -i /etc/hosts
echo "8.8.8.8 facebook.com" | sudo tee -i /etc/hosts
