#!/usr/bin/env bash

# Set the name of the private key
private_key_name="school"

# Number of bits in the key
key_bits=4096

# Passphrase to protect the key
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$key_bits" -N "$passphrase" -f "$private_key_name"
